#!/usr/bin/env python3

import sys
import time


def factorize_rsa(number):
    factors = []
    for i in range(2, int(number ** 0.5) + 1):
        while number % i == 0:
            factors.append(i)
            number //= i
    if number > 1:
        factors.append(number)
    return factors


def main():
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        return

    file_path = sys.argv[1]

    with open(file_path, 'r') as file:
        numbers = file.read().splitlines()

    start_time = time.time()

    for number in numbers:
        factors = factorize_rsa(int(number))
        prime_factors = [factor for factor in factors if all(factor % i != 0 for i in range(2, int(factor ** 0.5) + 1))]
        prime_factors.sort()

        print(f"{number}={prime_factors[0]}*{prime_factors[1]}")

    end_time = time.time()
    elapsed_time = end_time - start_time
    print(f"\nExecution time: {elapsed_time:.3f} seconds")

if __name__ == "__main__":
    main()
